language: elixir
elixir:
- 1.3.2
before_install:
- openssl aes-256-cbc -K $encrypted_944d6c2c1357_key -iv $encrypted_944d6c2c1357_iv
  -in cert_key.tar.enc -out cert_key.tar -d
- tar xvf cert_key.tar
